<?php
require_once('../scripts/student_validation.php');
require_once('../../../config/admin_server.php');
$add_side_bar = true;
include_once('../layouts/head_to_wrapper.php');
include_once('../layouts/topbar.php');
?>

<style>
    .table-width {
        padding-right: 75px;
        padding-left: 75px;
        margin-right: auto;
        margin-left: auto;
    }
    @media (min-width: 768px) {
        .table-width {
            width: 750px;
        }
    }
    @media (min-width: 992px) {
        .table-width {
            width: 970px;
        }
    }
    @media (min-width: 1200px) {
        .table-width {
            width: 1170px;
        }
    }
</style>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8" style="border: 1px solid #73AD21; ">
            <div class="card shadow-s border-0 rounded-lg mt-1">
                <?php
                if (isset($_POST['create_school_'])) {

                    $name = $_POST['name'];
                    $location = $_POST['address'];
                    $emis_number = $_POST['emis_number'];
                    $province = $_POST['province'];

                    $district = $_POST['district'];
                    $gps_lat = $_POST['gps_lat'];
                    $gps_long = $_POST['gps_long'];
                    $type = $_POST['type'];

                    $sql = "INSERT INTO schools ( `name`, `province`, `district`, `address`, `gps_lat`, `gps_long`, `emis_number`, `sch_type`) 
                    VALUES('$name','$province','$district' , '$location', '$emis_number','$gps_lat','$gps_long','$type')";

                    $success = mysqli_query($db, $sql);
                    if (!$success) {
                        die('Could not enter data: ' . mysqli_error($db));
                    }
                    echo '   <h3 style=" background-color: green">A new school has been added successfully</h3>';
                }
                ?>
                <div class="card-header"><h5 class="text-center my-2">Add New School</h5></div>
                <div class="card-body" style=" border-color: black ">
                    <form action="#" method="post" enctype="multipart/form-data">

                        <table class="table" id="" width="100%" cellspacing="9">
                            <!-- <tr> -->
                                <!-- <td class="text-left">Student Id:</td> Hide ID input since it's now autogenerated-->
                            <input id="stuId"type="hidden" name="studentId" placeholder="Enter EMIS Number">
                            <!-- </tr> -->
                            <tr>
                                <td style=" color: black"><b>Enter EMIS Number:</b></td>
                                <td class="text-right"><input id="stuName" type="text" name="emis_number" placeholder="Enter EMIS Number" required=""></td>
                            </tr>
                            <tr>                          
                                <td style=" color: black"><b>Enter School Name:</b></td>
                                <td class="text-right"><input type="text" name="name" placeholder="Enter School Name" required=""></td>
                            </tr>

                            <tr>                              
                                <td style=" color: black"><b>Enter School Address:</b></td>
                                <td class="text-right"><input type="text" name="address" placeholder="Enter School Address" required=""></td>
                            </tr>

                            <tr>
                                <td style=" color: black"><b>Province:</b></td>
                                <td class="text-right">
                                    <select name="province" id="class_id">                                            
                                        <option value="Central Province">Central Province </option>      
                                        <option value="Copperbelt Province">Copperbelt Province </option>
                                        <option value="Eastern Province">Eastern Province </option>      
                                        <option value="Luapula Province">Luapula Province  </option>
                                        <option value="Lusaka Province">Lusaka Province </option>      
                                        <option value="Muchinga Province">Muchinga Province </option>
                                        <option value="Northern Province">Northern Province </option>      
                                        <option value="North-Western Province">North-Western Province  </option>
                                        <option value="Southern Province">Southern Province </option>      
                                        <option value="Western Province ">Western Province  </option>
                                    </select>                            
                                </td>
                            </tr>

                            <tr>

                                <td style=" color: black"><b>District:</b></td>
                                <td class="text-right">
                                    <select name="district" id="class_id">                                            
                                        <option value="Kabwe">Kabwe </option>      
                                        <option value="Choma">Choma </option>                                      
                                    </select>                            
                                </td>
                            </tr>

                            <tr>
                                <td style=" color: black"><b>Type of School:</b></td>
                                <td class="text-right">
                                    <select name="type" id="class_id">                                            
                                        <option value="University">University </option>      
                                        <option value="College">College </option>                 
                                        <option value="Community School">Community School </option>     
                                        <option value="Primary School ">Primary School </option>
                                    </select>                            
                                </td>
                            </tr>

                            <tr>
                                <td style=" color: black"><b>Enter GPS Latitude  Location</td>
                                <td class="text-right"><input type="text" name="gps_lat" placeholder="Enter Latitude  Location" ></td>
                            </tr>

                            <tr>
                                <td style=" color: black"><b>Enter GPS longitude  Location:</b></td>
                                <td class="text-right"><input type="text" name="gps_long" placeholder="Enter longitude  Location" ></td>
                            </tr>

                            <td></td>
                            <td class="text-right"><input class="btn btn-sm btn-success " type="submit" name="create_school_"value="Submit"></td>

                        </table>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- Multi-Select suport -->
<link rel="stylesheet" href="../../../assets/select_box/vanillaSelectBox.css">
<script src="../../../assets/select_box/vanillaSelectBox.js"></script>
<script>
    let mySelect = new vanillaSelectBox("#subj", {
        maxWidth: 500,
        maxHeight: 400,
        minWidth: -1,
        search: true,
        disableSelectAll: true,
        placeHolder: "Assign subjects",
    });
</script>
<!-- End multi-select support  -->


<?php require_once('../layouts/footer_to_end.php'); ?>

